# Generated by Django 5.0.7 on 2024-07-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('proveedor', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('RESERVADO', 'Reservado'), ('NO_DISPONIBLE', 'No disponible')], default='DISPONIBLE', max_length=20)),
                ('comentario', models.TextField(max_length=500)),
            ],
        ),
    ]
