# Generated by Django 5.1.2 on 2024-11-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='profile_pics'),
        ),
    ]
