# Generated by Django 5.1.2 on 2024-11-04 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='default.jpg', upload_to='perfil_imagenes/')),
                ('nivel', models.IntegerField(default=1)),
                ('experiencia', models.IntegerField(default=0)),
                ('titulo', models.CharField(choices=[('NEOFITO', 'Neófito de la Cripta'), ('ACOLITO', 'Acolito de las sombras'), ('GUARDIAN', 'Guardián de la tumba'), ('SENIOR', 'Señor de la oscuridad'), ('MAESTRO', 'Maestro de la Cripta'), ('ARCHIMAGO', 'Archimago de las tinieblas'), ('LICH', 'Lich supremo')], default='NEOFITO', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
