# Generated by Django 5.1.2 on 2024-11-04 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfil_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='img/default-profile.png', upload_to='perfil_imagenes/'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.juego')),
                ('usuarios_inscritos', models.ManyToManyField(related_name='sesiones_inscritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sesiones',
            },
        ),
    ]
