# Generated by Django 5.1.2 on 2024-11-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_juego_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='comentario',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
