# Generated by Django 5.1.2 on 2024-11-28 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_juego_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='comentario',
            new_name='descripcion',
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='juegos_pdfs/')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuales', to='core.juego')),
            ],
        ),
    ]
