# Generated by Django 5.1.2 on 2024-11-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_comentario_juego_descripcion_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='manual',
        ),
    ]
