# Generated by Django 5.1.2 on 2024-11-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_juego_manual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual',
            options={'verbose_name_plural': 'Manuales'},
        ),
        migrations.AlterField(
            model_name='juego',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible para préstamo'), ('PRESTADO', 'Prestado'), ('RESERVADO', 'Reservado'), ('NO_DISPONIBLE', 'No disponible')], default='DISPONIBLE', max_length=20),
        ),
    ]
