# Generated by Django 5.1.2 on 2024-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_manual_options_alter_juego_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='video_tutorial',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
