# Generated by Django 5.1.2 on 2024-11-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_juego_video_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='jugadores_max',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='juego',
            name='jugadores_min',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
