# Generated by Django 5.1.2 on 2024-11-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('PRESTADO', 'Prestado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20),
        ),
    ]
