# Generated by Django 5.1.2 on 2024-11-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_prestamo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='atrasado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
