# Generated by Django 5.0.6 on 2024-12-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_noticia_autor_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.CharField(default='perfil_imagenes/default-profile.png', max_length=255),
        ),
    ]
