# Generated by Django 5.0.6 on 2024-12-02 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_perfil_imagen'),
        ('core', '0022_sesion_creador'),
    ]

    operations = [
    ]
