# Generated by Django 5.1.2 on 2024-12-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_0022_alter_perfil_imagen_0022_sesion_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
