# Generated by Django 5.1.2 on 2024-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_perfil_experiencia_perfil_cdlc_perfil_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
