# Generated by Django 5.1.2 on 2024-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sesion_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='lugar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
